# Generated by Django 3.1.7 on 2021-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
