# Generated by Django 3.1.7 on 2021-03-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='telefone',
            field=models.SlugField(),
        ),
    ]
