# Generated by Django 3.1.7 on 2021-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[('1', 'Teste')])),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
