# Generated by Django 3.1.7 on 2021-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Teste')]),
        ),
    ]
